{% set name = "pycudasirecon" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tlambert03/pycudasirecon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0d8543008115c85c481f5280777a270aab6c0c7dc733a6ada2b68afc88ea944c

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pydantic
    - cudasirecon
    - tifffile
    - typing_extensions

test:
  imports:
    - pycudasirecon
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tlambert03/pycudasirecon
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python wrapper for cudasirecon - GPU accelerated SIM reconstruction
  description: |
    This package provides a python wrapper and convenience functions for cudasirecon,
    a CUDA-accelerated implementation of the Gustafsson SIM reconstruction algorithm.
  doc_url: https://www.talleylambert.com/pycudasirecon/
  dev_url: https://github.com/tlambert03/pycudasirecon

extra:
  recipe-maintainers:
    - tlambert03
